INSERT INTO `trashes` (`id`, `trash_category_id`, `name`, `points`, `unit`, `image`, `created_at`, `updated_at`) VALUES
(1, 1, 'Milk Tea Container', 11.00, 'kg', 'milkteacontainer.png',  NULL, NULL),
(2, 1, 'Oil Bottle', 12.50, 'kg', 'oilbottle.png',  NULL, NULL),
(3, 1, 'Mineral Bottle', 7.25, 'kg', 'mineralbottle.png',  NULL, NULL),
(4, 1, 'Plastic Bag', 4.00, 'kg', 'plasticbag.png',  NULL, NULL),
(5, 1, 'Soft Drink Bottle', 7.25, 'kg', 'softdrinksbottle.png',  NULL, NULL),
(6, 1, 'Plastic Parcels', 4.50, 'kg', 'plasticparcels.png',  NULL, NULL),
(7, 1, 'Containers', 5.50, 'kg', 'container.png',  NULL, NULL),
(8, 1, 'Plastic Cup', 6.00, 'kg', 'cup.png',  NULL, NULL),
(9, 1, 'Sachet', 4.25, 'kg', 'sachet.png',  NULL, NULL),
(10, 2, 'A4 Paper', 0.25, 'kg', 'a4paper.png',  NULL, NULL),
(11, 2, 'Carton Box', 0.75, 'kg', 'cartonbox.png',  NULL, NULL),
(12, 2, 'Magazine', 1.00, 'kg', 'magazine.png',  NULL, NULL),
(13, 2, 'Newspaper', .75, 'kg', 'newspaper.png',  NULL, NULL),
(14, 2, 'Packaging Box', 1.25, 'kg', 'packagingbox.png',  NULL, NULL),
(15, 2, 'Tetra Pack', 1.50, 'kg', 'tetrapack.png',  NULL, NULL),
(16, 2, 'Paper Bag', .50, 'kg', 'paperbag.png',  NULL, NULL),
(17, 3, 'Fruits & Vegetables', 2.25, 'kg', 'vegetablefruit.png',  NULL, NULL),
(18, 3, 'Egg shells', 2.25, 'kg', 'eggshell.png',  NULL, NULL),
(19, 3, 'Nut shells', 2.50, 'kg', 'nutshell.png',  NULL, NULL),
(20, 3, 'Coffee ground', 2.25, 'kg', 'coffeeground.png',  NULL, NULL),
(21, 3, 'Tea bag', 3.75, 'kg', 'teabag.png',  NULL, NULL),
(22, 4, 'Clothes', 2.50, 'pcs', 'clothes.png',  NULL, NULL),
(23, 4, 'Blanket', 3.75, 'pcs', 'blanket.png',  NULL, NULL),
(24, 4, 'Bed Sheet', 4.00, 'pcs', 'bedsheet.png',  NULL, NULL),
(25, 5, 'Aluminum', 16.75, 'kg', 'aluminum.png',  NULL, NULL),
(26, 5, 'Cast Iron', 3.00, 'kg', 'castiron.png',  NULL, NULL),
(27, 5, 'Food Cans', 1.00, 'kg', 'foodcan.png',  NULL, NULL),
(28, 5, 'Soft Drink Cans', 1.25, 'kg', 'softdrinkcan.png',  NULL, NULL),
(29, 5, 'Copper', 83.25, 'kg', 'copper.png',  NULL, NULL),
(30, 5, 'Steel', 5.25, 'kg', 'steel.png',  NULL, NULL),
(31, 6, 'Bear Bottle', 0.50, 'pcs', 'beerbottle.png',  NULL, NULL),
(32, 6, 'Water Bottle', 0.25, 'pcs', 'waterbottle.png',  NULL, NULL),
(33, 6, 'Wine Bottle', 0.75, 'pcs', 'winebottle.png',  NULL, NULL),
(34, 6, 'Milk Bottle', 0.75, 'pcs', 'milkbottle.png',  NULL, NULL),
(35, 6, 'Liquor Bottle', 0.75, 'pcs', 'liquorbottle.png',  NULL, NULL),
(36, 6, 'Broken Glass', 2.75, 'kg', 'brokenglass.png',  NULL, NULL);
